"""
app.py — Main entry point for YouTube Video Summarizer.

This module contains ONLY backend / business logic:
  • Agent initialization
  • URL parsing & validation
  • AI response handling & error detection
  • Section parsing
  • Report generation

All UI rendering is delegated to ui.py.

"""

import re
import json
from pathlib import Path
import streamlit as st
from dotenv import load_dotenv

# Explicitly point to .env in the project root
load_dotenv(Path(__file__).resolve().parent / ".env")

from youtube_analyzer import build_youtube_agent
from ui import (
    setup_page,
    render_sidebar,
    render_header,
    render_input_section,
    render_output,
    render_error_rate_limit,
    render_footer,
)

def extract_video_id(url: str) -> str | None:
    """Pull the 11-char video ID out of any common YouTube URL format."""
    patterns = [
        r'(?:v=)([a-zA-Z0-9_-]{11})',
        r'(?:youtu\.be/)([a-zA-Z0-9_-]{11})',
        r'(?:embed/)([a-zA-Z0-9_-]{11})',
        r'(?:shorts/)([a-zA-Z0-9_-]{11})',
    ]
    for p in patterns:
        m = re.search(p, url)
        if m:
            return m.group(1)
    return None


def parse_sections(md_text: str) -> dict:
    """Split the agent's markdown response into named sections."""
    sections: dict[str, str] = {}
    current = None
    buffer: list[str] = []

    for line in md_text.splitlines():
        heading = re.match(r'^##\s+(.+)', line)
        if heading:
            if current:
                sections[current] = "\n".join(buffer).strip()
            current = heading.group(1).strip()
            buffer = []
        else:
            buffer.append(line)

    if current:
        sections[current] = "\n".join(buffer).strip()
    return sections


def build_download_text(sections: dict) -> str:
    """Stitch sections back into a clean plain-text file."""
    lines = ["=" * 50, "  YouTube Video Summary Report", "=" * 50, ""]
    for title, body in sections.items():
        lines.append(f"\n{'─' * 40}")
        lines.append(f"  {title}")
        lines.append(f"{'─' * 40}")
        lines.append(body)
    lines.append(f"\n{'=' * 50}")
    lines.append("Generated by YouTube Video Summarizer")
    return "\n".join(lines)


def recover_from_api_error(raw: str) -> tuple[str | None, str | None]:
    """Check if the raw response is a JSON API error.

    Returns:
        (recovered_content, error_message)
        - If the error contains usable content in 'failed_generation', return it.
        - If it's a fatal error, return (None, error_message).
        - If it's not an error at all, return (None, None).
    """
    if not (raw and raw.strip().startswith("{") and "error" in raw):
        return None, None  # Not an error

    try:
        err = json.loads(raw)
    except json.JSONDecodeError:
        return None, f"Unexpected response: {raw[:300]}"

    error_obj = err.get("error", {})
    error_code = error_obj.get("code", "")
    error_msg = error_obj.get("message", "Unknown API error")

    # tool_use_failed: Groq generated good content but fumbled the tool call.
    # The actual analysis is in 'failed_generation' — recover it.
    if error_code == "tool_use_failed":
        recovered = error_obj.get("failed_generation", "")
        if recovered and "##" in recovered:
            return recovered, None  # Recovered successfully

    return None, error_msg


def is_rate_limit_error(raw: str) -> bool:
    """Return True if the raw response contains a Groq rate-limit error."""
    return bool(raw and "rate_limit" in raw)


# 2. AGENT INIT (cached)
@st.cache_resource
def get_agent():
    return build_youtube_agent()

# 3. APP LAYOUT  (calls into ui.py for all rendering)
setup_page()
render_sidebar()
render_header()

video_url, run = render_input_section()

# 4. MAIN PROCESSING PIPELINE
if run:
    cleaned = video_url.strip()

    if not cleaned:
        st.warning("Please paste a valid YouTube link above.")
        st.stop()

    vid_id = extract_video_id(cleaned)
    
    if not vid_id:
        st.error("Invalid YouTube URL. Please provide a valid link.")
        st.stop()

    # Call the AI agent
    with st.spinner("AI is analyzing the video — hang tight..."):
        try:
            agent = get_agent()
            response = agent.run(
                f"Analyze this YouTube video thoroughly: {cleaned}"
            )
        except Exception as exc:
            st.error(f"Something went wrong: {exc}")
            st.stop()

    raw = response.content

    # Handle API errors (and recover content when possible)
    recovered, error_msg = recover_from_api_error(raw)
    if recovered:
        raw = recovered  # Use the recovered content instead
    elif error_msg:
        if is_rate_limit_error(raw):
            render_error_rate_limit()
        else:
            st.error(f"API Error: {error_msg}")
        st.stop()

    # Parse sections
    sections = parse_sections(raw)

    if not sections:
        st.warning("Could not parse structured sections — showing raw output.")
        st.markdown(raw)
        st.stop()

    # Render output
    download_text = build_download_text(sections)
    render_output(sections, vid_id, raw, download_text)

# 5. FOOTER (always visible)
render_footer()